---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: no
  vars:
    - username: vagrant
    - home_dir: "/home/{{ username }}"
  tasks:
    - name: req for pelican
      apt: name={{ item }} cache_valid_time=3600
      sudo: yes
      with_items:
        - python
        - python-setuptools
        - make
        - python-pip
    - name: pelican
      pip: name={{ item }} state=installed
      with_items:
        - pelican
        - markdown
      sudo: yes
    - include: ansible-vim/vim.yml
