---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: no
  vars:
    - username: vagrant
    - home_dir: "/home/{{ username }}"
  tasks:
    - name: req for pelican
      apt: name={{ item }}
      sudo: yes
      with_items:
        - python
        - python-setuptools
    - name: pelican
      easy_install: name=pelican
    - include: ansible-vim/vim.yml
